Add bookings
a-grebnev-91-tech/java-shareit pull request #3
Opened 2022-09-02 14:28 UTC by a-grebnev-91-tech

В коде есть несколько закомментированных TODO  потому что не согласен с той логикой, что прописана в тестах постмана, и после завершения проекта хочу вернуть логику которая на мой взгляд более правильна.

2022-09-03 08:03 UTC, kukolev requested changes

2022-09-03 08:03 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/domain/ItemServiceImpl.java
> +        /*
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-03 08:03 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartIsBeforeAndEndIsAfter(
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-09-03 08:03 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/JpaBookingRepository.java
> +    List<Booking> findAllByBookerIdAndItemIdAndEndDateInPast(Long bookerId, Long itemId, LocalDateTime now);
Здесь лучше придумать название метода попроще, т.к. есть аннотация `@Query` в которой прописана логика поиска.

2022-09-03 08:36 UTC, a-grebnev-91-tech commented on src/main/java/ru/practicum/shareit/item/domain/ItemServiceImpl.java
> +        /*
Запутает, если программист анализирует код без участия нервной системы...

2022-09-03 08:57 UTC, a-grebnev-91-tech commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartIsBeforeAndEndIsAfter(
А "ReactiveStreamsMongoClientDependsOnBeanFactoryPostProcessor" читаются хорошо?)))

2022-09-03 21:26 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartIsBeforeAndEndIsAfter(
Нет, тоже читаются плохо.

2022-09-03 21:28 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/domain/ItemServiceImpl.java
> +        /*
Это понятно. Разобраться что к чему можно всегда, но лучше экономить ресурсы нервной системы для чего-то более стоящего, чем решение вопросы "а почему автор это закомментировал, а не удалил?"

2022-09-03 21:34 UTC, kukolev requested changes

2022-09-03 21:34 UTC, kukolev commented on src/main/java/ru/practicum/shareit/exception/handler/CustomResponseEntityExceptionHandler.java
> +     protected ResponseEntity<Object> handleBookingStateIsNotSupported(BookingStateIsNotSupportedException ex, WebRequest request) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-03 21:34 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/controller/UserDto.java
> +//    @UniqueEmail(groups = {CreateInfo.class, PatchInfo.class}) // constraint passed to database for YP postman's tests
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-04 07:42 UTC, kukolev approved these changes

2022-09-04 13:17 UTC, merged